/**
 * Supabase type definitions.
 *
 * GENERATED by scripts/gen-types.mjs - do not edit by hand.
 * Re-run `node scripts/gen-types.mjs` after a schema migration.
 * Introspected straight from the live schema over DATABASE_URL,
 * so it stays correct without the Docker dependency that
 * `supabase gen types` needs.
 */

export type Database = {
  public: {
    Tables: {
      rgaios_agent_chat_messages: {
        Row: {
          id: string;
          organization_id: string;
          agent_id: string;
          user_id: string | null;
          role: string;
          content: string;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          agent_id: string;
          user_id?: string | null;
          role: string;
          content: string;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agent_chat_messages"]["Row"]>;
        Relationships: [];
      };
      rgaios_agent_file_chunks: {
        Row: {
          id: string;
          file_id: string;
          organization_id: string;
          agent_id: string;
          chunk_index: number;
          content: string;
          token_count: number | null;
          embedding: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          file_id: string;
          organization_id: string;
          agent_id: string;
          chunk_index: number;
          content: string;
          token_count?: number | null;
          embedding?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agent_file_chunks"]["Row"]>;
        Relationships: [];
      };
      rgaios_agent_files: {
        Row: {
          id: string;
          organization_id: string;
          agent_id: string;
          filename: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          uploaded_by: string | null;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          agent_id: string;
          filename: string;
          storage_path: string;
          mime_type?: string;
          size_bytes?: number;
          uploaded_by?: string | null;
          uploaded_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agent_files"]["Row"]>;
        Relationships: [];
      };
      rgaios_agent_skills: {
        Row: {
          agent_id: string;
          skill_id: string;
          organization_id: string;
          created_at: string;
        };
        Insert: {
          agent_id: string;
          skill_id: string;
          organization_id: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agent_skills"]["Row"]>;
        Relationships: [];
      };
      rgaios_agent_telegram_bots: {
        Row: {
          id: string;
          organization_id: string;
          agent_id: string;
          bot_id: number;
          bot_username: string | null;
          bot_first_name: string | null;
          bot_token: string;
          webhook_secret: string;
          status: string;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          agent_id: string;
          bot_id: number;
          bot_username?: string | null;
          bot_first_name?: string | null;
          bot_token: string;
          webhook_secret: string;
          status?: string;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agent_telegram_bots"]["Row"]>;
        Relationships: [];
      };
      rgaios_agents: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          title: string | null;
          role: string;
          reports_to: string | null;
          description: string | null;
          runtime: string;
          budget_monthly_usd: number;
          spent_monthly_usd: number;
          status: string;
          write_policy: Record<string, unknown>;
          created_at: string;
          updated_at: string;
          department: string | null;
          is_department_head: boolean;
          system_prompt: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          title?: string | null;
          role?: string;
          reports_to?: string | null;
          description?: string | null;
          runtime?: string;
          budget_monthly_usd?: number;
          spent_monthly_usd?: number;
          status?: string;
          write_policy?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
          department?: string | null;
          is_department_head?: boolean;
          system_prompt?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_agents"]["Row"]>;
        Relationships: [];
      };
      rgaios_approvals: {
        Row: {
          id: string;
          organization_id: string;
          routine_run_id: string | null;
          agent_id: string | null;
          tool_name: string;
          tool_args: Record<string, unknown>;
          reason: string | null;
          status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          routine_run_id?: string | null;
          agent_id?: string | null;
          tool_name: string;
          tool_args: Record<string, unknown>;
          reason?: string | null;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_approvals"]["Row"]>;
        Relationships: [];
      };
      rgaios_audit_log: {
        Row: {
          id: string;
          organization_id: string | null;
          ts: string;
          kind: string;
          actor_type: string | null;
          actor_id: string | null;
          detail: Record<string, unknown>;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          ts?: string;
          kind: string;
          actor_type?: string | null;
          actor_id?: string | null;
          detail?: Record<string, unknown>;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_audit_log"]["Row"]>;
        Relationships: [];
      };
      rgaios_brand_intakes: {
        Row: {
          id: string;
          organization_id: string;
          basic_info: Record<string, unknown>;
          social_presence: Record<string, unknown>;
          origin_story: Record<string, unknown>;
          business_model: Record<string, unknown>;
          target_audience: Record<string, unknown>;
          goals: Record<string, unknown>;
          challenges: Record<string, unknown>;
          brand_voice: Record<string, unknown>;
          competitors: Record<string, unknown>;
          content_messaging: Record<string, unknown>;
          sales: Record<string, unknown>;
          tools_systems: Record<string, unknown>;
          additional_context: Record<string, unknown>;
          call_data: Record<string, unknown>;
          full_transcript: Record<string, unknown> | null;
          submitted_at: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          basic_info?: Record<string, unknown>;
          social_presence?: Record<string, unknown>;
          origin_story?: Record<string, unknown>;
          business_model?: Record<string, unknown>;
          target_audience?: Record<string, unknown>;
          goals?: Record<string, unknown>;
          challenges?: Record<string, unknown>;
          brand_voice?: Record<string, unknown>;
          competitors?: Record<string, unknown>;
          content_messaging?: Record<string, unknown>;
          sales?: Record<string, unknown>;
          tools_systems?: Record<string, unknown>;
          additional_context?: Record<string, unknown>;
          call_data?: Record<string, unknown>;
          full_transcript?: Record<string, unknown> | null;
          submitted_at?: number | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_brand_intakes"]["Row"]>;
        Relationships: [];
      };
      rgaios_brand_profiles: {
        Row: {
          id: string;
          organization_id: string;
          version: number;
          content: string;
          status: string;
          generated_at: number;
          approved_at: number | null;
          approved_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          version?: number;
          content?: string;
          status?: string;
          generated_at: number;
          approved_at?: number | null;
          approved_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_brand_profiles"]["Row"]>;
        Relationships: [];
      };
      rgaios_company_chunks: {
        Row: {
          id: string;
          organization_id: string;
          source: string;
          source_id: string | null;
          chunk_index: number;
          content: string;
          token_count: number | null;
          embedding: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          source: string;
          source_id?: string | null;
          chunk_index: number;
          content: string;
          token_count?: number | null;
          embedding?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_company_chunks"]["Row"]>;
        Relationships: [];
      };
      rgaios_connections: {
        Row: {
          id: string;
          organization_id: string;
          provider_config_key: string;
          nango_connection_id: string;
          display_name: string | null;
          status: string;
          metadata: Record<string, unknown>;
          connected_at: string;
          updated_at: string;
          agent_id: string | null;
          user_id: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          provider_config_key: string;
          nango_connection_id: string;
          display_name?: string | null;
          status?: string;
          metadata?: Record<string, unknown>;
          connected_at?: string;
          updated_at?: string;
          agent_id?: string | null;
          user_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_connections"]["Row"]>;
        Relationships: [];
      };
      rgaios_custom_mcp_tools: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string;
          code_ts: string;
          status: string;
          loop_count: number;
          last_test_output: string | null;
          last_error: string | null;
          created_by_agent_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description: string;
          code_ts: string;
          status?: string;
          loop_count?: number;
          last_test_output?: string | null;
          last_error?: string | null;
          created_by_agent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_custom_mcp_tools"]["Row"]>;
        Relationships: [];
      };
      rgaios_insights: {
        Row: {
          id: string;
          organization_id: string;
          department: string | null;
          kind: string;
          severity: string;
          metric: string;
          current_value: number | null;
          prior_value: number | null;
          delta_pct: number | null;
          title: string;
          reason: string | null;
          suggested_action: string | null;
          status: string;
          generated_by_agent_id: string | null;
          created_at: string;
          acknowledged_at: string | null;
          dismissed_at: string | null;
          loop_count: number;
          last_attempt_at: string | null;
          resolved_at: string | null;
          approved_at: string | null;
          rejected_at: string | null;
          chat_state: string;
          chat_state_updated_at: string | null;
          escalated_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          department?: string | null;
          kind: string;
          severity?: string;
          metric: string;
          current_value?: number | null;
          prior_value?: number | null;
          delta_pct?: number | null;
          title: string;
          reason?: string | null;
          suggested_action?: string | null;
          status?: string;
          generated_by_agent_id?: string | null;
          created_at?: string;
          acknowledged_at?: string | null;
          dismissed_at?: string | null;
          loop_count?: number;
          last_attempt_at?: string | null;
          resolved_at?: string | null;
          approved_at?: string | null;
          rejected_at?: string | null;
          chat_state?: string;
          chat_state_updated_at?: string | null;
          escalated_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_insights"]["Row"]>;
        Relationships: [];
      };
      rgaios_invites: {
        Row: {
          token_hash: string;
          email: string;
          name: string | null;
          role: string;
          organization_id: string;
          invited_by: string | null;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
          allowed_departments: string[];
        };
        Insert: {
          token_hash: string;
          email: string;
          name?: string | null;
          role?: string;
          organization_id: string;
          invited_by?: string | null;
          expires_at: string;
          accepted_at?: string | null;
          created_at?: string;
          allowed_departments?: string[];
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_invites"]["Row"]>;
        Relationships: [];
      };
      rgaios_kalendly_availability: {
        Row: {
          id: string;
          organization_id: string;
          timezone: string;
          weekly_hours: Record<string, unknown>;
          date_overrides: Record<string, unknown>;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          timezone?: string;
          weekly_hours?: Record<string, unknown>;
          date_overrides?: Record<string, unknown>;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_kalendly_availability"]["Row"]>;
        Relationships: [];
      };
      rgaios_kalendly_bookings: {
        Row: {
          id: string;
          organization_id: string;
          event_type_id: string;
          event_type_slug: string;
          guest_name: string;
          guest_email: string;
          guest_timezone: string;
          custom_answers: Record<string, unknown>;
          start_utc: string;
          end_utc: string;
          google_event_id: string | null;
          meet_link: string | null;
          manage_token: string;
          status: string;
          rescheduled_to_booking_id: string | null;
          notified_agent_at: string | null;
          created_at: string;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          event_type_id: string;
          event_type_slug: string;
          guest_name: string;
          guest_email: string;
          guest_timezone: string;
          custom_answers?: Record<string, unknown>;
          start_utc: string;
          end_utc: string;
          google_event_id?: string | null;
          meet_link?: string | null;
          manage_token: string;
          status?: string;
          rescheduled_to_booking_id?: string | null;
          notified_agent_at?: string | null;
          created_at?: string;
          cancelled_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_kalendly_bookings"]["Row"]>;
        Relationships: [];
      };
      rgaios_kalendly_calendar_bindings: {
        Row: {
          id: string;
          organization_id: string;
          calendar_id: string;
          calendar_summary: string;
          default_timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          calendar_id: string;
          calendar_summary: string;
          default_timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_kalendly_calendar_bindings"]["Row"]>;
        Relationships: [];
      };
      rgaios_kalendly_event_types: {
        Row: {
          id: string;
          organization_id: string;
          slug: string;
          title: string;
          description: string;
          duration_minutes: number;
          color: string;
          location: Record<string, unknown>;
          rules: Record<string, unknown>;
          custom_questions: Record<string, unknown>;
          active: boolean;
          position: number;
          agent_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          slug: string;
          title: string;
          description?: string;
          duration_minutes: number;
          color?: string;
          location: Record<string, unknown>;
          rules: Record<string, unknown>;
          custom_questions?: Record<string, unknown>;
          active?: boolean;
          position?: number;
          agent_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_kalendly_event_types"]["Row"]>;
        Relationships: [];
      };
      rgaios_knowledge_files: {
        Row: {
          id: string;
          organization_id: string;
          title: string;
          tags: string[];
          storage_path: string;
          mime_type: string;
          size_bytes: number | null;
          uploaded_at: string;
          uploaded_by: string | null;
          bucket: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          title: string;
          tags?: string[];
          storage_path: string;
          mime_type?: string;
          size_bytes?: number | null;
          uploaded_at?: string;
          uploaded_by?: string | null;
          bucket?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_knowledge_files"]["Row"]>;
        Relationships: [];
      };
      rgaios_mini_saas: {
        Row: {
          id: string;
          organization_id: string;
          title: string;
          description: string | null;
          prompt: string;
          generated_html: string | null;
          status: string;
          generation_meta: Record<string, unknown>;
          created_by_agent_id: string | null;
          created_at: string;
          updated_at: string;
          deployed_url: string | null;
          deployed_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          title: string;
          description?: string | null;
          prompt: string;
          generated_html?: string | null;
          status?: string;
          generation_meta?: Record<string, unknown>;
          created_by_agent_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deployed_url?: string | null;
          deployed_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_mini_saas"]["Row"]>;
        Relationships: [];
      };
      rgaios_onboarding_documents: {
        Row: {
          id: string;
          organization_id: string;
          type: string;
          storage_url: string;
          filename: string;
          size: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          type?: string;
          storage_url: string;
          filename: string;
          size?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_onboarding_documents"]["Row"]>;
        Relationships: [];
      };
      rgaios_onboarding_knowledge: {
        Row: {
          id: string;
          kind: string;
          section_id: string | null;
          content: string;
          embedding: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kind: string;
          section_id?: string | null;
          content: string;
          embedding?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_onboarding_knowledge"]["Row"]>;
        Relationships: [];
      };
      rgaios_organization_memberships: {
        Row: {
          organization_id: string;
          user_id: string;
          role: string;
          created_at: string;
          allowed_departments: string[];
        };
        Insert: {
          organization_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
          allowed_departments?: string[];
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_organization_memberships"]["Row"]>;
        Relationships: [];
      };
      rgaios_organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
          updated_at: string;
          mcp_token: string | null;
          marketing: boolean;
          sales: boolean;
          fulfilment: boolean;
          finance: boolean;
          onboarding_completed: boolean;
          onboarding_step: number;
          messaging_channel: string | null;
          messaging_handle: string | null;
          slack_workspace_url: string | null;
          slack_channel_name: string | null;
          current_month: number | null;
          autonomous_mode: string | null;
          max_loop_iterations: number | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
          updated_at?: string;
          mcp_token?: string | null;
          marketing?: boolean;
          sales?: boolean;
          fulfilment?: boolean;
          finance?: boolean;
          onboarding_completed?: boolean;
          onboarding_step?: number;
          messaging_channel?: string | null;
          messaging_handle?: string | null;
          slack_workspace_url?: string | null;
          slack_channel_name?: string | null;
          current_month?: number | null;
          autonomous_mode?: string | null;
          max_loop_iterations?: number | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_organizations"]["Row"]>;
        Relationships: [];
      };
      rgaios_password_resets: {
        Row: {
          token_hash: string;
          user_id: string;
          expires_at: string;
          used_at: string | null;
          created_at: string;
        };
        Insert: {
          token_hash: string;
          user_id: string;
          expires_at: string;
          used_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_password_resets"]["Row"]>;
        Relationships: [];
      };
      rgaios_provisioning_queue: {
        Row: {
          id: string;
          organization_id: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          owner_email: string;
          owner_name: string | null;
          plan_name: string | null;
          status: string;
          vps_host: string | null;
          vps_url: string | null;
          dashboard_url: string | null;
          error: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          owner_email: string;
          owner_name?: string | null;
          plan_name?: string | null;
          status?: string;
          vps_host?: string | null;
          vps_url?: string | null;
          dashboard_url?: string | null;
          error?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_provisioning_queue"]["Row"]>;
        Relationships: [];
      };
      rgaios_routine_runs: {
        Row: {
          id: string;
          organization_id: string;
          routine_id: string;
          trigger_id: string | null;
          source: string;
          status: string;
          input_payload: Record<string, unknown> | null;
          output: Record<string, unknown> | null;
          error: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          routine_id: string;
          trigger_id?: string | null;
          source: string;
          status?: string;
          input_payload?: Record<string, unknown> | null;
          output?: Record<string, unknown> | null;
          error?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_routine_runs"]["Row"]>;
        Relationships: [];
      };
      rgaios_routine_triggers: {
        Row: {
          id: string;
          organization_id: string;
          routine_id: string;
          kind: string;
          enabled: boolean;
          config: Record<string, unknown>;
          public_id: string | null;
          created_at: string;
          last_fired_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          routine_id: string;
          kind: string;
          enabled?: boolean;
          config?: Record<string, unknown>;
          public_id?: string | null;
          created_at?: string;
          last_fired_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_routine_triggers"]["Row"]>;
        Relationships: [];
      };
      rgaios_routines: {
        Row: {
          id: string;
          organization_id: string;
          title: string;
          description: string | null;
          assignee_agent_id: string | null;
          status: string;
          kind: string;
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          title: string;
          description?: string | null;
          assignee_agent_id?: string | null;
          status?: string;
          kind?: string;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_routines"]["Row"]>;
        Relationships: [];
      };
      rgaios_sales_calls: {
        Row: {
          id: string;
          organization_id: string;
          source_type: string;
          source_url: string | null;
          filename: string | null;
          transcript: string | null;
          duration_sec: number | null;
          status: string;
          metadata: Record<string, unknown>;
          error: string | null;
          created_at: string;
          updated_at: string;
          insights: Record<string, unknown> | null;
          objections: string[];
          pain_points: string[];
          buying_signals: string[];
          analyzed_at: string | null;
          source: string;
          fireflies_id: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          source_type: string;
          source_url?: string | null;
          filename?: string | null;
          transcript?: string | null;
          duration_sec?: number | null;
          status?: string;
          metadata?: Record<string, unknown>;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
          insights?: Record<string, unknown> | null;
          objections?: string[];
          pain_points?: string[];
          buying_signals?: string[];
          analyzed_at?: string | null;
          source?: string;
          fireflies_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_sales_calls"]["Row"]>;
        Relationships: [];
      };
      rgaios_scheduled_calls: {
        Row: {
          id: string;
          organization_id: string;
          title: string;
          month: number;
          week: number;
          calendly_url: string | null;
          scheduled_at: number | null;
          completed: boolean;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          title: string;
          month: number;
          week: number;
          calendly_url?: string | null;
          scheduled_at?: number | null;
          completed?: boolean;
          notes?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_scheduled_calls"]["Row"]>;
        Relationships: [];
      };
      rgaios_schema_migrations: {
        Row: {
          filename: string;
          applied_at: string;
        };
        Insert: {
          filename: string;
          applied_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_schema_migrations"]["Row"]>;
        Relationships: [];
      };
      rgaios_scrape_snapshots: {
        Row: {
          id: string;
          organization_id: string;
          kind: string;
          url: string;
          title: string | null;
          content: string | null;
          embedding: string | null;
          status: string;
          error: string | null;
          scraped_at: string | null;
          created_at: string;
          metrics: Record<string, unknown>;
        };
        Insert: {
          id?: string;
          organization_id: string;
          kind: string;
          url: string;
          title?: string | null;
          content?: string | null;
          embedding?: string | null;
          status?: string;
          error?: string | null;
          scraped_at?: string | null;
          created_at?: string;
          metrics?: Record<string, unknown>;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_scrape_snapshots"]["Row"]>;
        Relationships: [];
      };
      rgaios_shared_memory: {
        Row: {
          id: string;
          organization_id: string;
          fact: string;
          source_agent_id: string | null;
          source_chat_id: number | null;
          importance: number;
          scope: string[];
          supersedes_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          fact: string;
          source_agent_id?: string | null;
          source_chat_id?: number | null;
          importance?: number;
          scope?: string[];
          supersedes_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_shared_memory"]["Row"]>;
        Relationships: [];
      };
      rgaios_slack_bindings: {
        Row: {
          id: string;
          organization_id: string;
          slack_team_id: string;
          slack_channel_id: string;
          slack_channel_name: string | null;
          agent_id: string;
          trigger_type: string;
          output_type: string;
          output_config: Record<string, unknown>;
          prompt_template: string | null;
          enabled: boolean;
          created_at: string;
          last_fired_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          slack_team_id: string;
          slack_channel_id: string;
          slack_channel_name?: string | null;
          agent_id: string;
          trigger_type: string;
          output_type: string;
          output_config?: Record<string, unknown>;
          prompt_template?: string | null;
          enabled?: boolean;
          created_at?: string;
          last_fired_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_slack_bindings"]["Row"]>;
        Relationships: [];
      };
      rgaios_software_access: {
        Row: {
          id: string;
          organization_id: string;
          platform: string;
          access_type: string;
          confirmed: boolean;
          notes: string | null;
          confirmed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          platform: string;
          access_type?: string;
          confirmed?: boolean;
          notes?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_software_access"]["Row"]>;
        Relationships: [];
      };
      rgaios_telegram_messages: {
        Row: {
          id: string;
          organization_id: string;
          connection_id: string | null;
          chat_id: number;
          sender_user_id: number | null;
          sender_username: string | null;
          sender_first_name: string | null;
          message_id: number;
          text: string | null;
          received_at: string;
          responded_at: string | null;
          response_text: string | null;
          placeholder_message_id: number | null;
          agent_telegram_bot_id: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          connection_id?: string | null;
          chat_id: number;
          sender_user_id?: number | null;
          sender_username?: string | null;
          sender_first_name?: string | null;
          message_id: number;
          text?: string | null;
          received_at?: string;
          responded_at?: string | null;
          response_text?: string | null;
          placeholder_message_id?: number | null;
          agent_telegram_bot_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_telegram_messages"]["Row"]>;
        Relationships: [];
      };
      rgaios_users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          image: string | null;
          password_hash: string | null;
          email_verified: string | null;
          created_at: string;
          updated_at: string;
          role: string;
          organization_id: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          image?: string | null;
          password_hash?: string | null;
          email_verified?: string | null;
          created_at?: string;
          updated_at?: string;
          role?: string;
          organization_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["rgaios_users"]["Row"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      array_to_halfvec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      array_to_sparsevec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      array_to_vector: {
        Args: Record<string, never>;
        Returns: string;
      };
      binary_quantize: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      cosine_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      halfvec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_accum: {
        Args: Record<string, never>;
        Returns: number[];
      };
      halfvec_add: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_avg: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_cmp: {
        Args: Record<string, never>;
        Returns: number;
      };
      halfvec_combine: {
        Args: Record<string, never>;
        Returns: number[];
      };
      halfvec_concat: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_eq: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_ge: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_gt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_in: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_l2_squared_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      halfvec_le: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_lt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_mul: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_ne: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      halfvec_negative_inner_product: {
        Args: Record<string, never>;
        Returns: number;
      };
      halfvec_out: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      halfvec_recv: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_send: {
        Args: Record<string, never>;
        Returns: string;
      };
      halfvec_spherical_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      halfvec_sub: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_to_float4: {
        Args: Record<string, never>;
        Returns: number[];
      };
      halfvec_to_sparsevec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      halfvec_to_vector: {
        Args: Record<string, never>;
        Returns: string;
      };
      halfvec_typmod_in: {
        Args: Record<string, never>;
        Returns: number;
      };
      hamming_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      hnsw_bit_support: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      hnsw_halfvec_support: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      hnsw_sparsevec_support: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      hnswhandler: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      inner_product: {
        Args: Record<string, never>;
        Returns: number;
      };
      ivfflat_bit_support: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      ivfflat_halfvec_support: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      ivfflathandler: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      jaccard_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      l1_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      l2_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      l2_norm: {
        Args: Record<string, never>;
        Returns: number;
      };
      l2_normalize: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      rgaios_atlas_coordinate_bucket: {
        Args: {
          t: string;
        };
        Returns: number;
      };
      rgaios_current_org_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      rgaios_match_agent_chunks: {
        Args: {
          p_agent_id: string;
          p_organization_id: string;
          p_query: string;
          p_top_k: number;
        };
        Returns: unknown;
      };
      rgaios_match_company_chunks: {
        Args: {
          p_org_id: string;
          p_query_embedding: string;
          p_match_count: number;
          p_min_similarity: number;
        };
        Returns: unknown;
      };
      rgaios_match_onboarding_knowledge: {
        Args: {
          p_query_embedding: string;
          p_match_count: number;
          p_min_similarity: number;
          p_section_id: string;
        };
        Returns: unknown;
      };
      rgaios_set_updated_at: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      sparsevec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      sparsevec_cmp: {
        Args: Record<string, never>;
        Returns: number;
      };
      sparsevec_eq: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_ge: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_gt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_in: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      sparsevec_l2_squared_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      sparsevec_le: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_lt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_ne: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      sparsevec_negative_inner_product: {
        Args: Record<string, never>;
        Returns: number;
      };
      sparsevec_out: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      sparsevec_recv: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      sparsevec_send: {
        Args: Record<string, never>;
        Returns: string;
      };
      sparsevec_to_halfvec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      sparsevec_to_vector: {
        Args: Record<string, never>;
        Returns: string;
      };
      sparsevec_typmod_in: {
        Args: Record<string, never>;
        Returns: number;
      };
      subvector: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_accum: {
        Args: Record<string, never>;
        Returns: number[];
      };
      vector_add: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_avg: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_cmp: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_combine: {
        Args: Record<string, never>;
        Returns: number[];
      };
      vector_concat: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_dims: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_eq: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_ge: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_gt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_in: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_l2_squared_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_le: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_lt: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_mul: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_ne: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      vector_negative_inner_product: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_norm: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_out: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      vector_recv: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_send: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_spherical_distance: {
        Args: Record<string, never>;
        Returns: number;
      };
      vector_sub: {
        Args: Record<string, never>;
        Returns: string;
      };
      vector_to_float4: {
        Args: Record<string, never>;
        Returns: number[];
      };
      vector_to_halfvec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      vector_to_sparsevec: {
        Args: Record<string, never>;
        Returns: Record<string, unknown>;
      };
      vector_typmod_in: {
        Args: Record<string, never>;
        Returns: number;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
